package org.hl.socialspherebackend.api.dto.authorization.response;

public enum AuthorizationErrorCode {
    USER_ALREADY_EXISTS,
    USERNAME_DOES_NOT_EXISTS,
    NOT_VALID_USER,
    NOT_VALID_USER_TOKEN,

    LOGIN_REQUEST_IS_NULL,
    USERNAME_IS_NULL,
    USERNAME_IS_BLANK,
    USERNAME_CONTAINS_WHITESPACE,
    USERNAME_LENGTH_IS_TOO_LONG,
    USERNAME_LENGTH_IS_TOO_SHORT,
    PASSWORD_IS_NULL,
    PASSWORD_IS_BLANK,
    PASSWORD_CONTAINS_WHITESPACE,
    PASSWORD_LENGTH_IS_TOO_LONG,
    PASSWORD_LENGTH_IS_TOO_SHORT,

}
