spring:
  application:
    name: SocialSphereBackend

  datasource:
    url: jdbc:sqlserver://localhost:1433;database=SocialSphere;trustServerCertificate=true;
    username: hubert
    password: root123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  liquibase:
    change-log: classpath:database/changelog.xml

  jpa:
    properties:
      hibernate:
        format_sql=true:

    open-in-view: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.hl.socialspherebackend:
        application:
          user: DEBUG
    org.springframework:
      jdbc:
        core: DEBUG
        datasource: DEBUG
      transaction: DEBUG
      hibernate: TRACE



jwt:
  secret: 951b507db97ad30ab856ce9e0751a0a22c3b4c83db0b1b75537cd93996fa4c58