DELETE FROM DATABASECHANGELOG

-- DROP CHAT
DROP TABLE IF EXISTS chat_bound_users;
ALTER TABLE chat DROP CONSTRAINT FK_CHAT_MESSAGE_1;
DROP TABLE IF EXISTS chat_message;
DROP TABLE IF EXISTS chat;

-- DROP POSTS
DROP TABLE IF EXISTS post_comment;
DROP TABLE IF EXISTS post_liked_by;
DROP TABLE IF EXISTS post_image;
DROP TABLE IF EXISTS post_notification;
DROP TABLE IF EXISTS post;

-- DROP USERS
DROP TABLE IF EXISTS authority;
DROP TABLE IF EXISTS user_friend_list;
DROP TABLE IF EXISTS user_profile_config;
DROP TABLE IF EXISTS user_profile;
DROP TABLE IF EXISTS user_profile_picture;
DROP TABLE IF EXISTS user_friend_request;
DROP TABLE IF EXISTS users;
