package org.hl.socialspherebackend.api.dto.post.response;

public enum PostErrorCode {
    POST_NOT_FOUND,
    POST_COMMENT_NOT_FOUND,
    USER_NOT_FOUND,
    USER_ALREADY_LIKES_POST,
    USER_DOES_NOT_LIKE_POST,

    POST_REQUEST_IS_NULL,
    POST_COMMENT_REQUEST_IS_NULL,
    CONTENT_IS_NULL,
    CONTENT_IS_BLANK,
    CONTENT_LENGTH_IS_TOO_SHORT,
    CONTENT_LENGTH_IS_TOO_LONG,
}
